### PR TITLE
US-0000017: DEMO: Create an AccountOperations Helper

### PR DESCRIPTION
**Pull request by swongcopado**
Please review this helper class introduced for User Story 17

### CODE REVIEW

**Review by andy-stevenckwong — COMMENTED** [review]
Class logic seems ok. 
Can you add some comments to describe what the logic does?

**Comment by andy-stevenckwong** [comment]
Class logic seems ok. Can you add some comments to better describe the logic of the helper?

**Comment by swongcopado** [comment]
Thanks. I've added some addtional documentation. Please review if this is better?

**Review by andy-stevenckwong — COMMENTED** [review]
Thanks for the added comments. Understand the logic better now.
I spotted a potential issue in line 24. Wouldn;t this cause a race condition?

**Comment by andy-stevenckwong** [comment]
Thanks for the added comments. Understand the logic better now.
I spotted a potential issue in line 24. Wouldn;t this cause a race condition?

**Comment by swongcopado** [comment]
Missed that. I've fixed that now! Thank you for the sharp eye!

**Review by andy-stevenckwong — APPROVED** [review]
Nice work. Thanks. Approved

**Comment by andy-stevenckwong** [comment]
Nice work. Thanks. Approved

**Pull request closed without merging**
